import type { QuizQuestion } from '../types.js';

const MOCK_QUESTIONS: Record<string, Record<string, QuizQuestion[]>> = {
  javascript: {
    beginner: [
      { id: 'js-b-1', question: 'What is the output of: console.log(typeof NaN)?', options: ["'undefined'", "'number'", "'NaN'", "'object'"], correctAnswer: "'number'", explanation: "Despite standing for 'Not a Number', NaN is actually of type 'number' in JavaScript.", code: 'console.log(typeof NaN);' },
      { id: 'js-b-2', question: 'Which keyword declares a block-scoped variable in JavaScript?', options: ['var', 'let', 'const', 'Both let and const'], correctAnswer: 'Both let and const', explanation: 'Both let and const declare block-scoped variables. const also prevents reassignment.', code: null },
      { id: 'js-b-3', question: 'What does "===" operator check in JavaScript?', options: ['Value only', 'Type only', 'Value and type', 'Reference only'], correctAnswer: 'Value and type', explanation: 'The strict equality operator (===) checks both value and type without performing type coercion.', code: null },
      { id: 'js-b-4', question: 'Which method is used to add an element to the end of an array?', options: ['push()', 'pop()', 'shift()', 'unshift()'], correctAnswer: 'push()', explanation: 'The push() method adds one or more elements to the end of an array and returns the new length.', code: null },
      { id: 'js-b-5', question: 'What is the correct way to declare an arrow function?', options: ['function => ()', '() => {}', '=> function() {}', 'arrow() => {}'], correctAnswer: '() => {}', explanation: 'Arrow functions use the => syntax: () => {} for no parameters, (x) => {} for one parameter.', code: null },
    ],
    intermediate: [
      { id: 'js-i-1', question: 'What is the output of: console.log(typeof NaN)?', options: ["'undefined'", "'number'", "'NaN'", "'object'"], correctAnswer: "'number'", explanation: "Despite standing for 'Not a Number', NaN is actually of type 'number' in JavaScript.", code: 'console.log(typeof NaN);' },
      { id: 'js-i-2', question: 'Which method is used to serialize an object into a JSON string in JavaScript?', options: ['JSON.stringify()', 'JSON.parse()', 'JSON.toText()', 'JSON.serialize()'], correctAnswer: 'JSON.stringify()', explanation: 'JSON.stringify() converts a JavaScript object into a JSON string, while JSON.parse() does the opposite.', code: 'const obj = { name: \'John\', age: 30 };\nconst jsonString = JSON.stringify(obj);' },
      { id: 'js-i-3', question: 'What is a closure in JavaScript?', options: ['A way to close the browser', 'A function that has access to its outer scope', 'A method to end loops', 'A type of error handling'], correctAnswer: 'A function that has access to its outer scope', explanation: 'A closure is a function that retains access to variables from its outer (enclosing) scope, even after the outer function has returned.', code: null },
      { id: 'js-i-4', question: 'What does the "this" keyword refer to in an arrow function?', options: ['The function itself', 'The global object', 'The enclosing lexical scope', 'undefined'], correctAnswer: 'The enclosing lexical scope', explanation: 'Arrow functions do not have their own "this" binding. They inherit "this" from the enclosing lexical scope.', code: null },
      { id: 'js-i-5', question: 'What is the time complexity of Array.prototype.indexOf()?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], correctAnswer: 'O(n)', explanation: 'indexOf() performs a linear search through the array, checking each element until it finds a match, resulting in O(n) time complexity.', code: null },
    ],
    advanced: [
      { id: 'js-a-1', question: 'What is the event loop in JavaScript?', options: ['A way to loop through events', 'A mechanism that handles asynchronous operations', 'A type of for loop', 'A design pattern'], correctAnswer: 'A mechanism that handles asynchronous operations', explanation: 'The event loop is the mechanism that allows JavaScript to perform non-blocking operations by offloading operations to the system kernel whenever possible.', code: null },
      { id: 'js-a-2', question: 'What is the difference between microtasks and macrotasks?', options: ['They are the same thing', 'Microtasks have higher priority', 'Macrotasks have higher priority', 'It depends on the browser'], correctAnswer: 'Microtasks have higher priority', explanation: 'Microtasks (Promise callbacks, queueMicrotask) are executed before macrotasks (setTimeout, setInterval) after the current task completes.', code: null },
      { id: 'js-a-3', question: 'What does WeakMap prevent?', options: ['Memory leaks by allowing garbage collection', 'Type errors', 'Runtime exceptions', 'Syntax errors'], correctAnswer: 'Memory leaks by allowing garbage collection', explanation: 'WeakMap holds weak references to keys, allowing them to be garbage collected when no other references exist, preventing memory leaks.', code: null },
      { id: 'js-a-4', question: 'What is the purpose of Symbol in JavaScript?', options: ['To create random numbers', 'To create unique identifiers', 'To format strings', 'To create mathematical symbols'], correctAnswer: 'To create unique identifiers', explanation: 'Symbol creates a unique and immutable identifier. It is primarily used as a key for object properties to avoid naming collisions.', code: null },
      { id: 'js-a-5', question: 'How does the Proxy object work?', options: ['It creates a server proxy', 'It intercepts and customizes object operations', 'It clones objects', 'It creates immutable objects'], correctAnswer: 'It intercepts and customizes object operations', explanation: 'Proxy allows you to create a wrapper that intercepts and customizes fundamental operations on objects (get, set, etc.).', code: null },
    ],
  },
  react: {
    beginner: [
      { id: 'react-b-1', question: 'What is JSX?', options: ['A template engine', 'A syntax extension for JavaScript', 'A CSS framework', 'A database query language'], correctAnswer: 'A syntax extension for JavaScript', explanation: 'JSX is a syntax extension for JavaScript that allows writing HTML-like code in React components.', code: null },
      { id: 'react-b-2', question: 'What is the correct way to pass a prop called "name" to a React component?', options: ['<Component {name} />', '<Component name={name} />', "<Component name='name' />", '<Component props={name} />'], correctAnswer: '<Component name={name} />', explanation: 'Props are passed as attributes to React components, with the value in curly braces for JavaScript expressions.', code: 'function Welcome(props) {\n  return <h1>Hello, {props.name}</h1>;\n}\n\n<Welcome name={user.name} />' },
      { id: 'react-b-3', question: 'What hook would you use to run side effects in a function component?', options: ['useState', 'useEffect', 'useContext', 'useReducer'], correctAnswer: 'useEffect', explanation: 'useEffect is the React hook designed for handling side effects like data fetching, subscriptions, or DOM manipulation.', code: 'useEffect(() => {\n  document.title = `Hello, ${name}`;\n}, [name]);' },
      { id: 'react-b-4', question: 'What does useState return?', options: ['A single value', 'An array with state and setter', 'An object', 'A promise'], correctAnswer: 'An array with state and setter', explanation: 'useState returns an array with two elements: the current state value and a function to update it.', code: null },
      { id: 'react-b-5', question: 'How do you handle events in React?', options: ['Using addEventListener', 'Using inline event handlers like onClick', 'Using jQuery', 'Using document.querySelector'], correctAnswer: 'Using inline event handlers like onClick', explanation: 'React uses synthetic events and inline handlers like onClick, onChange, etc. rather than traditional DOM event listeners.', code: null },
    ],
    intermediate: [
      { id: 'react-i-1', question: 'What is the Virtual DOM?', options: ['A browser API', 'A lightweight copy of the real DOM', 'A CSS framework', 'A server-side rendering technique'], correctAnswer: 'A lightweight copy of the real DOM', explanation: 'The Virtual DOM is a lightweight JavaScript representation of the real DOM that React uses to optimize rendering by calculating minimal DOM changes.', code: null },
      { id: 'react-i-2', question: 'What is the purpose of React.memo?', options: ['To write memos in code', 'To memoize components and prevent unnecessary re-renders', 'To create memo data structures', 'To add comments to components'], correctAnswer: 'To memoize components and prevent unnecessary re-renders', explanation: 'React.memo is a higher-order component that memoizes the result and skips re-rendering if the props haven\'t changed.', code: null },
      { id: 'react-i-3', question: 'What is the difference between useEffect and useLayoutEffect?', options: ['They are identical', 'useLayoutEffect runs synchronously after DOM mutations', 'useEffect runs before painting', 'useLayoutEffect is deprecated'], correctAnswer: 'useLayoutEffect runs synchronously after DOM mutations', explanation: 'useLayoutEffect fires synchronously after all DOM mutations, before the browser paints. useEffect fires asynchronously after painting.', code: null },
      { id: 'react-i-4', question: 'How do you share state between sibling components?', options: ['Using global variables', 'Lifting state up to their common parent', 'Using localStorage', 'CSS variables'], correctAnswer: 'Lifting state up to their common parent', explanation: 'When sibling components need to share state, you lift the state up to their closest common parent and pass it down via props.', code: null },
      { id: 'react-i-5', question: 'What is React Suspense used for?', options: ['Error handling', 'Waiting for asynchronous operations before rendering', 'Adding animations', 'State management'], correctAnswer: 'Waiting for asynchronous operations before rendering', explanation: 'Suspense lets components wait for data or other async operations before rendering, showing a fallback while loading.', code: null },
    ],
    advanced: [
      { id: 'react-a-1', question: 'What is a React fiber?', options: ['A fiber-optic cable', 'The reconciliation algorithm in React 16+', 'A CSS layout system', 'A testing framework'], correctAnswer: 'The reconciliation algorithm in React 16+', explanation: 'Fiber is React\'s reconciliation algorithm introduced in React 16, enabling incremental rendering and better scheduling of work.', code: null },
      { id: 'react-a-2', question: 'What are error boundaries in React?', options: ['Components that catch JavaScript errors in child component trees', 'A way to handle HTTP errors', 'A form validation technique', 'CSS error handling'], correctAnswer: 'Components that catch JavaScript errors in child component trees', explanation: 'Error boundaries are React components that catch JavaScript errors anywhere in their child component tree and display a fallback UI.', code: null },
      { id: 'react-a-3', question: 'What is the purpose of React.StrictMode?', options: ['To make code stricter', 'To identify potential problems in the application', 'To prevent errors', 'To enforce TypeScript'], correctAnswer: 'To identify potential problems in the application', explanation: 'StrictMode is a development-only feature that highlights potential problems like deprecated lifecycle methods and side effects.', code: null },
      { id: 'react-a-4', question: 'How do you optimize re-renders in a large list?', options: ['Use more state', 'Use React.memo and useCallback', 'Use CSS animations', 'Increase the number of components'], correctAnswer: 'Use React.memo and useCallback', explanation: 'React.memo prevents unnecessary re-renders of list items, and useCallback stabilizes function references to avoid breaking memoization.', code: null },
      { id: 'react-a-5', question: 'What is concurrent mode in React?', options: ['Running React on multiple threads', 'A way to interrupt rendering to handle more urgent updates', 'A server-side rendering technique', 'A pattern for managing concurrent API calls'], correctAnswer: 'A way to interrupt rendering to handle more urgent updates', explanation: 'Concurrent Mode allows React to interrupt a long-running render to handle more urgent updates like user input, making the UI more responsive.', code: null },
    ],
  },
  html: {
    beginner: [
      { id: 'html-b-1', question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'], correctAnswer: 'Hyper Text Markup Language', explanation: 'HTML stands for Hyper Text Markup Language, the standard markup language for creating web pages.', code: null },
      { id: 'html-b-2', question: 'Which HTML element creates the largest heading?', options: ['<heading>', '<h6>', '<h1>', '<head>'], correctAnswer: '<h1>', explanation: 'The <h1> element creates the largest heading in HTML. Headings range from <h1> (largest) to <h6> (smallest).', code: null },
      { id: 'html-b-3', question: 'What is the correct HTML element for inserting a line break?', options: ['<break>', '<lb>', '<br>', '<newline>'], correctAnswer: '<br>', explanation: 'The <br> element inserts a single line break in HTML.', code: null },
      { id: 'html-b-4', question: 'Which attribute specifies an alternate text for an image?', options: ['title', 'src', 'alt', 'name'], correctAnswer: 'alt', explanation: 'The alt attribute provides alternate text for an image, which is displayed if the image cannot be loaded and is used by screen readers.', code: null },
      { id: 'html-b-5', question: 'What is the correct HTML for creating a hyperlink?', options: ['<a url="https://example.com">', '<a href="https://example.com">', '<link href="https://example.com">', '<hyperlink>https://example.com</hyperlink>'], correctAnswer: '<a href="https://example.com">', explanation: 'The <a> element with the href attribute creates a hyperlink in HTML.', code: null },
    ],
    intermediate: [
      { id: 'html-i-1', question: 'What is the purpose of the <meta> viewport tag?', options: ['To set the page title', 'To control layout on mobile browsers', 'To add metadata for SEO', 'To link stylesheets'], correctAnswer: 'To control layout on mobile browsers', explanation: 'The viewport meta tag controls the layout viewport dimensions and scaling on mobile browsers, essential for responsive design.', code: null },
      { id: 'html-i-2', question: 'What is the difference between <section> and <div>?', options: ['No difference', '<section> has semantic meaning', '<div> is deprecated', '<section> is for styling only'], correctAnswer: '<section> has semantic meaning', explanation: '<section> represents a thematic grouping of content with semantic meaning, while <div> is a generic container with no semantic value.', code: null },
      { id: 'html-i-3', question: 'Which attribute makes a form input mandatory?', options: ['mandatory', 'required', 'must', 'validate'], correctAnswer: 'required', explanation: 'The required attribute specifies that an input field must be filled in before submitting the form.', code: null },
      { id: 'html-i-4', question: 'What is the purpose of the <datalist> element?', options: ['To create a dropdown menu', 'To provide autocomplete suggestions for input fields', 'To store data locally', 'To create a data table'], correctAnswer: 'To provide autocomplete suggestions for input fields', explanation: 'The <datalist> element provides a predefined list of options for an input field, enabling autocomplete functionality.', code: null },
      { id: 'html-i-5', question: 'What does the defer attribute do on a script tag?', options: ['Delays script loading until page load', 'Executes the script after the document is parsed', 'Makes the script asynchronous', 'Prevents the script from running'], correctAnswer: 'Executes the script after the document is parsed', explanation: 'The defer attribute tells the browser to download the script in parallel and execute it after the document has been parsed.', code: null },
    ],
    advanced: [
      { id: 'html-a-1', question: 'What is the purpose of the <template> element?', options: ['To create reusable HTML content that is not rendered until used', 'To style HTML elements', 'To create JavaScript templates', 'To cache HTML content'], correctAnswer: 'To create reusable HTML content that is not rendered until used', explanation: 'The <template> element holds content that is not rendered on page load but can be cloned and inserted via JavaScript.', code: null },
      { id: 'html-a-2', question: 'What is the difference between async and defer on script tags?', options: ['No difference', 'Async executes ASAP, defer waits for parsing', 'Defer is faster', 'Async is for external scripts only'], correctAnswer: 'Async executes ASAP, defer waits for parsing', explanation: 'async downloads and executes the script as soon as it\'s available. defer downloads in parallel but executes after the document is parsed.', code: null },
      { id: 'html-a-3', question: 'What is Shadow DOM?', options: ['A dark theme for web pages', 'An encapsulated DOM subtree hidden from the main document', 'A security feature', 'A way to hide elements'], correctAnswer: 'An encapsulated DOM subtree hidden from the main document', explanation: 'Shadow DOM provides encapsulation by creating a separate DOM subtree that is hidden from the main document, enabling component isolation.', code: null },
      { id: 'html-a-4', question: 'Which attribute allows custom data to be stored on HTML elements?', options: ['data-custom', 'data-*', 'custom-data', 'info'], correctAnswer: 'data-*', explanation: 'The data-* attributes allow you to store custom data on HTML elements. The * can be replaced with any name.', code: null },
      { id: 'html-a-5', question: 'What is the purpose of the <picture> element?', options: ['To display image galleries', 'To provide multiple sources for responsive images', 'To draw graphics', 'To add photo effects'], correctAnswer: 'To provide multiple sources for responsive images', explanation: 'The <picture> element contains multiple <source> elements allowing different images for different viewport conditions.', code: null },
    ],
  },
  css: {
    beginner: [
      { id: 'css-b-1', question: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Sheets'], correctAnswer: 'Cascading Style Sheets', explanation: 'CSS stands for Cascading Style Sheets, used to style and layout web pages.', code: null },
      { id: 'css-b-2', question: 'Which property changes the text color?', options: ['text-color', 'font-color', 'color', 'text-style'], correctAnswer: 'color', explanation: 'The color property sets the text color of an element. text-color and font-color are not valid CSS properties.', code: null },
      { id: 'css-b-3', question: 'What is the default value of the position property?', options: ['relative', 'absolute', 'static', 'fixed'], correctAnswer: 'static', explanation: 'The default value of the position property is static, meaning elements are positioned according to normal document flow.', code: null },
      { id: 'css-b-4', question: 'Which property is used to change the font size?', options: ['text-size', 'font-size', 'size', 'font-size-adjust'], correctAnswer: 'font-size', explanation: 'The font-size property is used to set the size of text in an element.', code: null },
      { id: 'css-b-5', question: 'How do you select an element with id "demo"?', options: ['.demo', '#demo', 'demo', '*demo'], correctAnswer: '#demo', explanation: 'The # selector targets an element by its id attribute. The . selector targets by class name.', code: null },
    ],
    intermediate: [
      { id: 'css-i-1', question: 'What is CSS Flexbox primarily used for?', options: ['Creating animations', 'Laying out items in one dimension', 'Creating grids', 'Adding shadows'], correctAnswer: 'Laying out items in one dimension', explanation: 'Flexbox is primarily designed for one-dimensional layouts (rows or columns). CSS Grid is better for two-dimensional layouts.', code: null },
      { id: 'css-i-2', question: 'What does "box-sizing: border-box" do?', options: ['Removes borders', 'Includes padding and border in element width/height', 'Adds a box around the element', 'Makes the element responsive'], correctAnswer: 'Includes padding and border in element width/height', explanation: 'border-box makes the width and height include padding and border, rather than adding them on top.', code: null },
      { id: 'css-i-3', question: 'What is the z-index property used for?', options: ['Zooming elements', 'Stacking order of positioned elements', 'Setting element size', 'Creating z-axis animations'], correctAnswer: 'Stacking order of positioned elements', explanation: 'z-index controls the stacking order of positioned elements. Higher values appear on top of lower values.', code: null },
      { id: 'css-i-4', question: 'What is the difference between em and rem units?', options: ['No difference', 'em is relative to parent, rem to root', 'rem is relative to parent, em to root', 'Both are fixed units'], correctAnswer: 'em is relative to parent, rem to root', explanation: 'em units are relative to the parent element\'s font size, while rem units are relative to the root element\'s font size.', code: null },
      { id: 'css-i-5', question: 'Which property is used to create space between an element\'s border and its content?', options: ['margin', 'spacing', 'padding', 'gap'], correctAnswer: 'padding', explanation: 'padding creates space between an element\'s content and its border, while margin creates space outside the border.', code: null },
    ],
    advanced: [
      { id: 'css-a-1', question: 'What is CSS Grid used for?', options: ['One-dimensional layouts', 'Two-dimensional layouts', 'Animations', 'Transitions'], correctAnswer: 'Two-dimensional layouts', explanation: 'CSS Grid excels at two-dimensional layouts (rows and columns simultaneously), while Flexbox is better for one-dimensional layouts.', code: null },
      { id: 'css-a-2', question: 'What does the "fr" unit represent in CSS Grid?', options: ['Frame', 'Fraction', 'Frequency', 'Format'], correctAnswer: 'Fraction', explanation: 'The fr unit represents a fraction of the available space in the grid container. It distributes space proportionally.', code: null },
      { id: 'css-a-3', question: 'What is CSS Custom Properties (Variables)?', options: ['CSS preprocessor features', 'Native CSS variables starting with --', 'JavaScript variables in CSS', 'External CSS files'], correctAnswer: 'Native CSS variables starting with --', explanation: 'CSS Custom Properties are native CSS variables that start with -- and can be defined and used throughout stylesheets.', code: null },
      { id: 'css-a-4', question: 'What is the "clamp()" function used for?', options: ['Clamping values between min and max', 'Creating animations', 'Setting colors', 'Adding borders'], correctAnswer: 'Clamping values between min and max', explanation: 'clamp(min, preferred, max) sets a value that scales between a minimum and maximum based on the preferred value, commonly used for responsive typography.', code: null },
      { id: 'css-a-5', question: 'What is the difference between :where() and :is()?', options: ['No difference', ':is() has higher specificity, :where() has zero specificity', ':where() is deprecated', ':is() is for classes only'], correctAnswer: ':is() has higher specificity, :where() has zero specificity', explanation: 'Both :is() and :where() take a list of selectors, but :where() always has zero specificity while :is() takes the specificity of its most specific argument.', code: null },
    ],
  },
  node: {
    beginner: [
      { id: 'node-b-1', question: 'What is Node.js?', options: ['A frontend framework', 'A JavaScript runtime built on Chrome\'s V8 engine', 'A database', 'A CSS preprocessor'], correctAnswer: "A JavaScript runtime built on Chrome's V8 engine", explanation: 'Node.js is a JavaScript runtime built on Chrome\'s V8 JavaScript engine for building server-side applications.', code: null },
      { id: 'node-b-2', question: 'Which module is used to create a server in Node.js?', options: ['fs', 'http', 'path', 'url'], correctAnswer: 'http', explanation: 'The http module provides functionality to create HTTP servers and make HTTP requests in Node.js.', code: null },
      { id: 'node-b-3', question: 'What is npm?', options: ['Node Package Manager', 'New Project Manager', 'Node Process Monitor', 'Network Protocol Manager'], correctAnswer: 'Node Package Manager', explanation: 'npm (Node Package Manager) is the default package manager for Node.js, used to install and manage dependencies.', code: null },
      { id: 'node-b-4', question: 'What does the "require" function do?', options: ['Creates a new module', 'Imports a module', 'Requires a password', 'Checks dependencies'], correctAnswer: 'Imports a module', explanation: 'The require() function is used to import modules in CommonJS, which is Node.js\'s module system.', code: null },
      { id: 'node-b-5', question: 'What is the event loop in Node.js?', options: ['A for loop', 'A mechanism for handling asynchronous operations', 'A debugging tool', 'A testing framework'], correctAnswer: 'A mechanism for handling asynchronous operations', explanation: 'The event loop is the mechanism that allows Node.js to perform non-blocking I/O operations.', code: null },
    ],
    intermediate: [
      { id: 'node-i-1', question: 'What is middleware in Express.js?', options: ['Hardware components', 'Functions that have access to request and response objects', 'Database connectors', 'Client-side libraries'], correctAnswer: 'Functions that have access to request and response objects', explanation: 'Middleware functions have access to the request object, response object, and the next middleware function in the cycle.', code: null },
      { id: 'node-i-2', question: 'What is the difference between process.nextTick() and setImmediate()?', options: ['No difference', 'nextTick executes before setImmediate', 'setImmediate executes before nextTick', 'They are from different libraries'], correctAnswer: 'nextTick executes before setImmediate', explanation: 'process.nextTick() fires before the event loop continues (microtask), while setImmediate() fires on the next iteration of the event loop (macrotask).', code: null },
      { id: 'node-i-3', question: 'What are streams in Node.js?', options: ['Arrays', 'Objects for handling streaming data', 'CSS features', 'HTML elements'], correctAnswer: 'Objects for handling streaming data', explanation: 'Streams are objects that let you read data from a source or write data to a destination in a continuous fashion, useful for large data.', code: null },
      { id: 'node-i-4', question: 'What is the purpose of the "cluster" module?', options: ['To group files', 'To create child processes that share the same server port', 'To connect to databases', 'To manage dependencies'], correctAnswer: 'To create child processes that share the same server port', explanation: 'The cluster module allows Node.js to create child processes (workers) that share the same server port, enabling load balancing.', code: null },
      { id: 'node-i-5', question: 'What is the difference between __dirname and process.cwd()?', options: ['No difference', '__dirname is the directory of the current module, cwd is the working directory', 'cwd is faster', '__dirname is deprecated'], correctAnswer: '__dirname is the directory of the current module, cwd is the working directory', explanation: '__dirname returns the directory of the current module file, while process.cwd() returns the current working directory of the Node.js process.', code: null },
    ],
    advanced: [
      { id: 'node-a-1', question: 'What is the libuv library responsible for?', options: ['HTTP parsing', 'Event loop and async I/O', 'V8 compilation', 'Package management'], correctAnswer: 'Event loop and async I/O', explanation: 'libuv is the C library that provides the event loop and handles asynchronous I/O operations in Node.js.', code: null },
      { id: 'node-a-2', question: 'What is a Worker Thread in Node.js?', options: ['A web worker', 'A separate thread for CPU-intensive tasks', 'A database connection', 'A socket connection'], correctAnswer: 'A separate thread for CPU-intensive tasks', explanation: 'Worker Threads allow executing CPU-intensive JavaScript in parallel on separate threads, avoiding blocking the main event loop.', code: null },
      { id: 'node-a-3', question: 'What is the V8 engine?', options: ['A database engine', 'Google\'s open-source JavaScript engine', 'A web server', 'A testing framework'], correctAnswer: "Google's open-source JavaScript engine", explanation: 'V8 is Google\'s open-source high-performance JavaScript engine used in Chrome and Node.js to compile JavaScript to machine code.', code: null },
      { id: 'node-a-4', question: 'What is the purpose of the Buffer class?', options: ['To create UI elements', 'To handle binary data directly in memory', 'To manage HTTP requests', 'To handle file paths'], correctAnswer: 'To handle binary data directly in memory', explanation: 'The Buffer class provides a way to handle binary data directly in memory, essential for file I/O and network operations.', code: null },
      { id: 'node-a-5', question: 'What is Zero Downtime Deployment?', options: ['Deploying without tests', 'Deploying without interrupting service', 'Removing old code', 'A deployment strategy for small apps'], correctAnswer: 'Deploying without interrupting service', explanation: 'Zero Downtime Deployment is a strategy where new versions of an application are deployed without any interruption to the current service.', code: null },
    ],
  },
};

export function getQuestions(topic: string, difficulty: string): QuizQuestion[] {
  const topicQuestions = MOCK_QUESTIONS[topic];
  if (!topicQuestions) return generateGenericQuestions(topic, difficulty);
  const difficultyQuestions = topicQuestions[difficulty];
  if (!difficultyQuestions) {
    const fallback = Object.keys(topicQuestions)[0];
    return topicQuestions[fallback] ?? generateGenericQuestions(topic, difficulty);
  }
  return difficultyQuestions;
}

function generateGenericQuestions(topic: string, difficulty: string): QuizQuestion[] {
  return [
    {
      id: `gen-${topic}-${difficulty}-1`,
      question: `What is a key feature of ${topic} in a ${difficulty} context?`,
      options: ['Component-based architecture', 'Dynamic typing system', 'Static type checking', 'Just-in-time compilation'],
      correctAnswer: 'Component-based architecture',
      explanation: `This is a fundamental concept in ${topic} that allows for modular and reusable code.`,
      code: null,
    },
    {
      id: `gen-${topic}-${difficulty}-2`,
      question: `How do you create a ${topic} application from scratch?`,
      options: [`Using the create-${topic} command line tool`, 'Using a starter template', 'Manually setting up the configuration', 'All of the above'],
      correctAnswer: 'All of the above',
      explanation: `There are multiple ways to start a ${topic} project, including CLI tools, templates, or manual configuration.`,
      code: null,
    },
  ];
}
